version: '3.6'

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./:${CONTAINER_PROJECT_DIR}
        ports:
            - "8000:8000"