version: '3.6'

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:${CONTAINER_PROJECT_DIR}
            - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "8000:8000"