version: '3.6'

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:${CONTAINER_PROJECT_DIR}
        working_dir: ${CONTAINER_PROJECT_DIR}
        ports:
            - "8000:8000"